ALTER USER SATHYANEU SET DISABLE_MFA = TRUE;
ALTER USER DBT_DEV SET DISABLE_MFA = TRUE;


CREATE OR REPLACE AUTHENTICATION POLICY FRED_AUTH_POLICY
  AUTHENTICATION_METHODS = ('PASSWORD', 'KEYPAIR')
  CLIENT_TYPES = ('SNOWFLAKE_CLI', 'SNOWFLAKE_UI')
  MFA_ENROLLMENT = OPTIONAL;

ALTER USER DBT_DEV SET AUTHENTICATION POLICY FRED_AUTH_POLICY;

