--!jinja

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"FRED_DB"."{{env}}_INTEGRATIONS"."{{env}}_DB_OBJECTS"')
    FROM '@"FRED_DB"."INTEGRATIONS"."GIT_REPO"/branches/"{{branch}}"/notebooks/DB_OBJECTS/'
    QUERY_WAREHOUSE = 'FRED_WH'
    MAIN_FILE = 'DB_OBJECTS.ipynb';

ALTER NOTEBOOK "FRED_DB"."{{env}}_INTEGRATIONS"."{{env}}_DB_OBJECTS" ADD LIVE VERSION FROM LAST;

EXECUTE NOTEBOOK "FRED_DB"."{{env}}_INTEGRATIONS"."{{env}}_DB_OBJECTS"();

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"FRED_DB"."{{env}}_FRED_RAW"."{{env}}_LOAD_FROM_STAGE"')
    FROM '@"FRED_DB"."INTEGRATIONS"."GIT_REPO"/branches/"{{branch}}"/notebooks/LOAD_FROM_STAGE/'
    QUERY_WAREHOUSE = 'FRED_WH'
    MAIN_FILE = 'LOAD_FROM_STAGE.ipynb';

ALTER NOTEBOOK "FRED_DB"."{{env}}_FRED_RAW"."{{env}}_LOAD_FROM_STAGE" ADD LIVE VERSION FROM LAST;

EXECUTE NOTEBOOK "FRED_DB"."{{env}}_FRED_RAW"."{{env}}_LOAD_FROM_STAGE"();
