-- 1. user must be connected to fred_setup/or other database of your choice
-- 2. make sure to run the pre_deployment_script_1 before executing this script 
-- 3. replace GITHUB_SECRET_USERNAME and GITHUB_SECRET_PASSWORD with true values

-- Secrets (schema level)
USE ROLE FRED_ROLE;

USE DATABASE FRED_SETUP;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA DBO;

SET GITHUB_SECRET_USERNAME = 'your-username'
SET GITHUB_SECRET_PASSWORD = 'your-password';
SET GITHUB_URL_PREFIX = 'https://github.com/bigdata-org';
SET GITHUB_REPO_ORIGIN = 'https://github.com/bigdata-org/fred_data_extraction.git';

CREATE OR REPLACE WAREHOUSE FRED_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
USE WAREHOUSE FRED_WH;

CREATE OR REPLACE DATABASE FRED_DB;
USE DATABASE FRED_DB;

CREATE OR REPLACE SCHEMA INTEGRATIONS;

CREATE OR REPLACE SECRET FRED_DB.INTEGRATIONS.GITHUB_SECRET
  TYPE = password
  USERNAME = $GITHUB_SECRET_USERNAME
  PASSWORD = $GITHUB_SECRET_PASSWORD;

CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ($GITHUB_URL_PREFIX)
  ALLOWED_AUTHENTICATION_SECRETS = (FRED_DB.INTEGRATIONS.GITHUB_SECRET)
  ENABLED = TRUE;

-- Git Repository
CREATE OR REPLACE GIT REPOSITORY FRED_DB.INTEGRATIONS.GIT_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = FRED_DB.INTEGRATIONS.GITHUB_SECRET
  ORIGIN = $GITHUB_REPO_ORIGIN;

  