USE ROLE ACCOUNTADMIN;

--ROLE
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE  FRED_ROLE;
-- GRANT ROLE FRED_ROLE TO SYSADMIN;
GRANT ROLE FRED_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE FRED_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE FRED_ROLE;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FRED_ROLE;


--DATABASE
CREATE OR REPLACE DATABASE  FRED_DB;
GRANT OWNERSHIP ON DATABASE FRED_DB TO ROLE FRED_ROLE;

--WAREHOUSE
CREATE OR REPLACE WAREHOUSE FRED_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE FRED_WH TO ROLE FRED_ROLE;

USE ROLE FRED_ROLE;
USE WAREHOUSE FRED_WH;
USE DATABASE FRED_DB;

--SCHEMA
CREATE OR REPLACE SCHEMA EXTERNAL_DATA;
CREATE OR REPLACE SCHEMA RAW_FRED;
CREATE OR REPLACE SCHEMA HARMONIZED;
CREATE OR REPLACE SCHEMA ANALYTICS;

--EXTERNAL DATA OBJECTS
USE SCHEMA EXTERNAL_DATA;
--PARQUET FORMAT FOR EFFICIENT STORAGE 
CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY ;

DROP STORAGE INTEGRATION my_gcs_integration;

CREATE OR REPLACE STORAGE INTEGRATION my_gcs_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'GCS'
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('*');
   --  STORAGE_BLOCKED_LOCATIONS = ('gcs://dow30-datapipeline/fred_data/sensitive/');

GRANT USAGE ON INTEGRATION my_gcs_integration TO ROLE FRED_ROLE;
-- GRANT USAGE ON INTEGRATION my_gcs_integration TO SCHEMA EXTERNAL_DATA;


--STAGE
 CREATE OR REPLACE STAGE FRED_RAW_STAGE
    -- URL ='gs://storage.cloud.google.com/dow30-datapipeline/fred_data/data.csv'
    URL='gcs://dow30-datapipeline/'
    STORAGE_INTEGRATION = my_gcs_integration
    ;

GRANT USAGE ON STAGE FRED_RAW_STAGE TO ROLE FRED_ROLE;


 